// Catálogo de Jugadores del Mundial 2026 - Fonda Fanegas Comunio
// Organizado por Selecciones Nacionales en lugar de por posiciones.

window.PLAYERS_POOL = [
  // --- ARGENTINA ---
  { id: "gk_martinez", nombre: "Emiliano Martínez", posicion: "portero", precio: 4000000, pais: "Argentina", flag: "🇦🇷" },
  { id: "df_romero", nombre: "Cristian Romero", posicion: "defensa", precio: 3500000, pais: "Argentina", flag: "🇦🇷" },
  { id: "df_otamendi", nombre: "Nicolás Otamendi", posicion: "defensa", precio: 1200000, pais: "Argentina", flag: "🇦🇷" },
  { id: "mf_mcallister", nombre: "Alexis Mac Allister", posicion: "mediocampista", precio: 4200000, pais: "Argentina", flag: "🇦🇷" },
  { id: "fw_messi", nombre: "Lionel Messi", posicion: "delantero", precio: 10000000, pais: "Argentina", flag: "🇦🇷" },
  { id: "fw_lautaro", nombre: "Lautaro Martínez", posicion: "delantero", precio: 7500000, pais: "Argentina", flag: "🇦🇷" },
  { id: "fw_alvarez", nombre: "Julián Álvarez", posicion: "delantero", precio: 4800000, pais: "Argentina", flag: "🇦🇷" },

  // --- ESPAÑA ---
  { id: "gk_simon", nombre: "Unai Simón", posicion: "portero", precio: 4000000, pais: "España", flag: "🇪🇸" },
  { id: "gk_raya", nombre: "David Raya", posicion: "portero", precio: 3500000, pais: "España", flag: "🇪🇸" },
  { id: "gk_jgarcia", nombre: "Joan García", posicion: "portero", precio: 1800000, pais: "España", flag: "🇪🇸" },
  { id: "df_llorente", nombre: "Marcos Llorente", posicion: "defensa", precio: 3000000, pais: "España", flag: "🇪🇸" },
  { id: "df_porro", nombre: "Pedro Porro", posicion: "defensa", precio: 3200000, pais: "España", flag: "🇪🇸" },
  { id: "df_egarcia", nombre: "Eric García", posicion: "defensa", precio: 2000000, pais: "España", flag: "🇪🇸" },
  { id: "df_pubill", nombre: "Marc Pubill", posicion: "defensa", precio: 1800000, pais: "España", flag: "🇪🇸" },
  { id: "df_laporte", nombre: "Aymeric Laporte", posicion: "defensa", precio: 2500000, pais: "España", flag: "🇪🇸" },
  { id: "df_cubarsi", nombre: "Pau Cubarsí", posicion: "defensa", precio: 3000000, pais: "España", flag: "🇪🇸" },
  { id: "df_cucurella", nombre: "Marc Cucurella", posicion: "defensa", precio: 3200000, pais: "España", flag: "🇪🇸" },
  { id: "df_grimaldo", nombre: "Alejandro Grimaldo", posicion: "defensa", precio: 3800000, pais: "España", flag: "🇪🇸" },
  { id: "mf_rodri", nombre: "Rodri Hernández", posicion: "mediocampista", precio: 9000000, pais: "España", flag: "🇪🇸" },
  { id: "mf_pedri", nombre: "Pedri González", posicion: "mediocampista", precio: 7500000, pais: "España", flag: "🇪🇸" },
  { id: "mf_fabian", nombre: "Fabián Ruiz", posicion: "mediocampista", precio: 3500000, pais: "España", flag: "🇪🇸" },
  { id: "mf_zubimendi", nombre: "Martín Zubimendi", posicion: "mediocampista", precio: 4500000, pais: "España", flag: "🇪🇸" },
  { id: "mf_gavi", nombre: "Gavi", posicion: "mediocampista", precio: 6000000, pais: "España", flag: "🇪🇸" },
  { id: "mf_merino", nombre: "Mikel Merino", posicion: "mediocampista", precio: 3800000, pais: "España", flag: "🇪🇸" },
  { id: "mf_baena", nombre: "Álex Baena", posicion: "mediocampista", precio: 4000000, pais: "España", flag: "🇪🇸" },
  { id: "fw_yamal", nombre: "Lamine Yamal", posicion: "delantero", precio: 10000000, pais: "España", flag: "🇪🇸" },
  { id: "fw_nwilliams", nombre: "Nico Williams", posicion: "delantero", precio: 7000000, pais: "España", flag: "🇪🇸" },
  { id: "fw_oyarzabal", nombre: "Mikel Oyarzabal", posicion: "delantero", precio: 4000000, pais: "España", flag: "🇪🇸" },
  { id: "fw_olmo", nombre: "Dani Olmo", posicion: "delantero", precio: 6500000, pais: "España", flag: "🇪🇸" },
  { id: "fw_ftorres", nombre: "Ferran Torres", posicion: "delantero", precio: 3500000, pais: "España", flag: "🇪🇸" },
  { id: "fw_pino", nombre: "Yeremy Pino", posicion: "delantero", precio: 2800000, pais: "España", flag: "🇪🇸" },
  { id: "fw_iglesias", nombre: "Borja Iglesias", posicion: "delantero", precio: 2000000, pais: "España", flag: "🇪🇸" },
  { id: "fw_vmunoz", nombre: "Víctor Muñoz", posicion: "delantero", precio: 1200000, pais: "España", flag: "🇪🇸" },

  // --- FRANCIA ---
  { id: "gk_maignan", nombre: "Mike Maignan", posicion: "portero", precio: 4500000, pais: "Francia", flag: "🇫🇷" },
  { id: "gk_risser", nombre: "Robin Risser", posicion: "portero", precio: 1500000, pais: "Francia", flag: "🇫🇷" },
  { id: "gk_samba", nombre: "Brice Samba", posicion: "portero", precio: 2500000, pais: "Francia", flag: "🇫🇷" },
  { id: "df_digne", nombre: "Lucas Digne", posicion: "defensa", precio: 2800000, pais: "Francia", flag: "🇫🇷" },
  { id: "df_gusto", nombre: "Malo Gusto", posicion: "defensa", precio: 3500000, pais: "Francia", flag: "🇫🇷" },
  { id: "df_lhernandez", nombre: "Lucas Hernández", posicion: "defensa", precio: 3800000, pais: "Francia", flag: "🇫🇷" },
  { id: "df_thernandez", nombre: "Theo Hernández", posicion: "defensa", precio: 4500000, pais: "Francia", flag: "🇫🇷" },
  { id: "df_konate", nombre: "Ibrahima Konaté", posicion: "defensa", precio: 4200000, pais: "Francia", flag: "🇫🇷" },
  { id: "df_kounde", nombre: "Jules Koundé", posicion: "defensa", precio: 4600000, pais: "Francia", flag: "🇫🇷" },
  { id: "df_lacroix", nombre: "Maxence Lacroix", posicion: "defensa", precio: 3000000, pais: "Francia", flag: "🇫🇷" },
  { id: "df_saliba", nombre: "William Saliba", posicion: "defensa", precio: 5200000, pais: "Francia", flag: "🇫🇷" },
  { id: "df_upamecano", nombre: "Dayot Upamecano", posicion: "defensa", precio: 4000000, pais: "Francia", flag: "🇫🇷" },
  { id: "mf_kante", nombre: "N'Golo Kanté", posicion: "mediocampista", precio: 3000000, pais: "Francia", flag: "🇫🇷" },
  { id: "mf_kone", nombre: "Manu Koné", posicion: "mediocampista", precio: 3200000, pais: "Francia", flag: "🇫🇷" },
  { id: "mf_rabiot", nombre: "Adrien Rabiot", posicion: "mediocampista", precio: 3500000, pais: "Francia", flag: "🇫🇷" },
  { id: "mf_tchouameni", nombre: "Aurélien Tchouaméni", posicion: "mediocampista", precio: 5000000, pais: "Francia", flag: "🇫🇷" },
  { id: "mf_zaireemery", nombre: "Warren Zaïre-Emery", posicion: "mediocampista", precio: 4800000, pais: "Francia", flag: "🇫🇷" },
  { id: "fw_akliouche", nombre: "Maghnes Akliouche", posicion: "delantero", precio: 3000000, pais: "Francia", flag: "🇫🇷" },
  { id: "fw_barcola", nombre: "Bradley Barcola", posicion: "delantero", precio: 5500000, pais: "Francia", flag: "🇫🇷" },
  { id: "fw_cherki", nombre: "Rayan Cherki", posicion: "delantero", precio: 3800000, pais: "Francia", flag: "🇫🇷" },
  { id: "fw_dembele", nombre: "Ousmane Dembélé", posicion: "delantero", precio: 6000000, pais: "Francia", flag: "🇫🇷" },
  { id: "fw_doue", nombre: "Désiré Doué", posicion: "delantero", precio: 3500000, pais: "Francia", flag: "🇫🇷" },
  { id: "fw_mateta", nombre: "Jean-Philippe Mateta", posicion: "delantero", precio: 3200000, pais: "Francia", flag: "🇫🇷" },
  { id: "fw_mbappe", nombre: "Kylian Mbappé", posicion: "delantero", precio: 12000000, pais: "Francia", flag: "🇫🇷" },
  { id: "fw_olise", nombre: "Michael Olise", posicion: "delantero", precio: 6500000, pais: "Francia", flag: "🇫🇷" },
  { id: "fw_thuram", nombre: "Marcus Thuram", posicion: "delantero", precio: 5000000, pais: "Francia", flag: "🇫🇷" },

  // --- ALEMANIA ---
  { id: "gk_neuer", nombre: "Manuel Neuer", posicion: "portero", precio: 2000000, pais: "Alemania", flag: "🇩🇪" },
  { id: "gk_baumann", nombre: "Oliver Baumann", posicion: "portero", precio: 1500000, pais: "Alemania", flag: "🇩🇪" },
  { id: "gk_nubel", nombre: "Alexander Nübel", posicion: "portero", precio: 2200000, pais: "Alemania", flag: "🇩🇪" },
  { id: "df_kimmich", nombre: "Joshua Kimmich", posicion: "defensa", precio: 4500000, pais: "Alemania", flag: "🇩🇪" },
  { id: "df_tah", nombre: "Jonathan Tah", posicion: "defensa", precio: 3500000, pais: "Alemania", flag: "🇩🇪" },
  { id: "df_rudiger", nombre: "Antonio Rüdiger", posicion: "defensa", precio: 4000000, pais: "Alemania", flag: "🇩🇪" },
  { id: "df_schlotterbeck", nombre: "Nico Schlotterbeck", posicion: "defensa", precio: 3800000, pais: "Alemania", flag: "🇩🇪" },
  { id: "df_anton", nombre: "Waldemar Anton", posicion: "defensa", precio: 2500000, pais: "Alemania", flag: "🇩🇪" },
  { id: "df_raum", nombre: "David Raum", posicion: "defensa", precio: 2800000, pais: "Alemania", flag: "🇩🇪" },
  { id: "df_thiaw", nombre: "Malick Thiaw", posicion: "defensa", precio: 2600000, pais: "Alemania", flag: "🇩🇪" },
  { id: "df_brown", nombre: "Nathaniel Brown", posicion: "defensa", precio: 1200000, pais: "Alemania", flag: "🇩🇪" },
  { id: "mf_goretzka", nombre: "Leon Goretzka", posicion: "mediocampista", precio: 2500000, pais: "Alemania", flag: "🇩🇪" },
  { id: "mf_pavlovic", nombre: "Aleksandar Pavlović", posicion: "mediocampista", precio: 3000000, pais: "Alemania", flag: "🇩🇪" },
  { id: "mf_musiala", nombre: "Jamal Musiala", posicion: "mediocampista", precio: 8500000, pais: "Alemania", flag: "🇩🇪" },
  { id: "mf_wirtz", nombre: "Florian Wirtz", posicion: "mediocampista", precio: 8800000, pais: "Alemania", flag: "🇩🇪" },
  { id: "mf_nmecha", nombre: "Felix Nmecha", posicion: "mediocampista", precio: 2400000, pais: "Alemania", flag: "🇩🇪" },
  { id: "mf_gross", nombre: "Pascal Groß", posicion: "mediocampista", precio: 1800000, pais: "Alemania", flag: "🇩🇪" },
  { id: "mf_stiller", nombre: "Angelo Stiller", posicion: "mediocampista", precio: 2600000, pais: "Alemania", flag: "🇩🇪" },
  { id: "mf_amiri", nombre: "Nadiem Amiri", posicion: "mediocampista", precio: 2000000, pais: "Alemania", flag: "🇩🇪" },
  { id: "fw_havertz", nombre: "Kai Havertz", posicion: "delantero", precio: 5500000, pais: "Alemania", flag: "🇩🇪" },
  { id: "fw_sane", nombre: "Leroy Sané", posicion: "delantero", precio: 3500000, pais: "Alemania", flag: "🇩🇪" },
  { id: "fw_woltemade", nombre: "Nick Woltemade", posicion: "delantero", precio: 1500000, pais: "Alemania", flag: "🇩🇪" },
  { id: "fw_undav", nombre: "Deniz Undav", posicion: "delantero", precio: 3200000, pais: "Alemania", flag: "🇩🇪" },
  { id: "fw_beier", nombre: "Maximilian Beier", posicion: "delantero", precio: 2800000, pais: "Alemania", flag: "🇩🇪" },
  { id: "fw_leweling", nombre: "Jamie Leweling", posicion: "delantero", precio: 2200000, pais: "Alemania", flag: "🇩🇪" },
  { id: "fw_karl", nombre: "Lennart Karl", posicion: "delantero", precio: 1200000, pais: "Alemania", flag: "🇩🇪" },

  // --- INGLATERRA ---
  { id: "gk_pickford", nombre: "Jordan Pickford", posicion: "portero", precio: 2500000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "gk_dhenderson", nombre: "Dean Henderson", posicion: "portero", precio: 2200000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "gk_trafford", nombre: "James Trafford", posicion: "portero", precio: 1500000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "df_stones", nombre: "John Stones", posicion: "defensa", precio: 3800000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "df_guehi", nombre: "Marc Guéhi", posicion: "defensa", precio: 3500000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "df_konsa", nombre: "Ezri Konsa", posicion: "defensa", precio: 2800000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "df_burn", nombre: "Dan Burn", posicion: "defensa", precio: 1800000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "df_quansah", nombre: "Jarell Quansah", posicion: "defensa", precio: 2200000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "df_rjames", nombre: "Reece James", posicion: "defensa", precio: 3000000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "df_livramento", nombre: "Tino Livramento", posicion: "defensa", precio: 2500000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "df_oreilly", nombre: "Nico O'Reilly", posicion: "defensa", precio: 1400000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "df_spence", nombre: "Djed Spence", posicion: "defensa", precio: 1600000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "mf_rice", nombre: "Declan Rice", posicion: "mediocampista", precio: 5800000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "mf_bellingham", nombre: "Jude Bellingham", posicion: "mediocampista", precio: 9500000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "mf_anderson", nombre: "Elliot Anderson", posicion: "mediocampista", precio: 2400000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "mf_mainoo", nombre: "Kobbie Mainoo", posicion: "mediocampista", precio: 3200000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "mf_rogers", nombre: "Morgan Rogers", posicion: "mediocampista", precio: 2800000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "mf_eze", nombre: "Eberechi Eze", posicion: "mediocampista", precio: 4000000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "mf_jhenderson", nombre: "Jordan Henderson", posicion: "mediocampista", precio: 1200000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "fw_kane", nombre: "Harry Kane", posicion: "delantero", precio: 9000000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "fw_saka", nombre: "Bukayo Saka", posicion: "delantero", precio: 8500000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "fw_rashford", nombre: "Marcus Rashford", posicion: "delantero", precio: 4500000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "fw_gordon", nombre: "Anthony Gordon", posicion: "delantero", precio: 4000000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "fw_madueke", nombre: "Noni Madueke", posicion: "delantero", precio: 3200000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "fw_watkins", nombre: "Ollie Watkins", posicion: "delantero", precio: 4500000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "fw_toney", nombre: "Ivan Toney", posicion: "delantero", precio: 3800000, pais: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },

  // --- CROACIA ---
  { id: "gk_livakovic", nombre: "Dominik Livakovic", posicion: "portero", precio: 2500000, pais: "Croacia", flag: "🇭🇷" },
  { id: "gk_kotarski", nombre: "Dominik Kotarski", posicion: "portero", precio: 1800000, pais: "Croacia", flag: "🇭🇷" },
  { id: "gk_pandur", nombre: "Ivor Pandur", posicion: "portero", precio: 1200000, pais: "Croacia", flag: "🇭🇷" },
  { id: "df_gvardiol", nombre: "Josko Gvardiol", posicion: "defensa", precio: 5500000, pais: "Croacia", flag: "🇭🇷" },
  { id: "df_caletacar", nombre: "Duje Caleta-Car", posicion: "defensa", precio: 2400000, pais: "Croacia", flag: "🇭🇷" },
  { id: "df_sutalo", nombre: "Josip Sutalo", posicion: "defensa", precio: 2800000, pais: "Croacia", flag: "🇭🇷" },
  { id: "df_stanisic", nombre: "Josip Stanisic", posicion: "defensa", precio: 3000000, pais: "Croacia", flag: "🇭🇷" },
  { id: "df_pongracic", nombre: "Marin Pongracic", posicion: "defensa", precio: 2000000, pais: "Croacia", flag: "🇭🇷" },
  { id: "df_erlic", nombre: "Martin Erlic", posicion: "defensa", precio: 1600000, pais: "Croacia", flag: "🇭🇷" },
  { id: "df_vuskovic", nombre: "Luka Vuskovic", posicion: "defensa", precio: 1800000, pais: "Croacia", flag: "🇭🇷" },
  { id: "mf_modric", nombre: "Luka Modric", posicion: "mediocampista", precio: 3500000, pais: "Croacia", flag: "🇭🇷" },
  { id: "mf_kovacic", nombre: "Mateo Kovacic", posicion: "mediocampista", precio: 4000000, pais: "Croacia", flag: "🇭🇷" },
  { id: "mf_mpasalic", nombre: "Mario Pasalic", posicion: "mediocampista", precio: 3000000, pais: "Croacia", flag: "🇭🇷" },
  { id: "mf_vlasic", nombre: "Nikola Vlasic", posicion: "mediocampista", precio: 2800000, pais: "Croacia", flag: "🇭🇷" },
  { id: "mf_lsucic", nombre: "Luka Sucic", posicion: "mediocampista", precio: 2600000, pais: "Croacia", flag: "🇭🇷" },
  { id: "mf_baturina", nombre: "Martin Baturina", posicion: "mediocampista", precio: 2400000, pais: "Croacia", flag: "🇭🇷" },
  { id: "mf_jakic", nombre: "Kristijan Jakic", posicion: "mediocampista", precio: 2000000, pais: "Croacia", flag: "🇭🇷" },
  { id: "mf_psucic", nombre: "Petar Sucic", posicion: "mediocampista", precio: 2200000, pais: "Croacia", flag: "🇭🇷" },
  { id: "mf_moro", nombre: "Nikola Moro", posicion: "mediocampista", precio: 1800000, pais: "Croacia", flag: "🇭🇷" },
  { id: "mf_fruk", nombre: "Toni Fruk", posicion: "mediocampista", precio: 1500000, pais: "Croacia", flag: "🇭🇷" },
  { id: "fw_perisic", nombre: "Ivan Perisic", posicion: "delantero", precio: 2000000, pais: "Croacia", flag: "🇭🇷" },
  { id: "fw_kramaric", nombre: "Andrej Kramaric", posicion: "delantero", precio: 3000000, pais: "Croacia", flag: "🇭🇷" },
  { id: "fw_budimir", nombre: "Ante Budimir", posicion: "delantero", precio: 2800000, pais: "Croacia", flag: "🇭🇷" },
  { id: "fw_macpasalic", nombre: "Marco Pasalic", posicion: "delantero", precio: 2200000, pais: "Croacia", flag: "🇭🇷" },
  { id: "fw_musa", nombre: "Petar Musa", posicion: "delantero", precio: 2400000, pais: "Croacia", flag: "🇭🇷" },
  { id: "fw_matanovic", nombre: "Igor Matanovic", posicion: "delantero", precio: 2000000, pais: "Croacia", flag: "🇭🇷" },

  // --- MARRUECOS ---
  { id: "gk_bono", nombre: "Yassine Bounou", posicion: "portero", precio: 2500000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "gk_munir", nombre: "Munir Mohamedi", posicion: "portero", precio: 1200000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "gk_tagnaouti", nombre: "Ahmed Tagnaouti", posicion: "portero", precio: 800000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "df_hakimi", nombre: "Achraf Hakimi", posicion: "defensa", precio: 5500000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "df_mazraoui", nombre: "Noussair Mazraoui", posicion: "defensa", precio: 3500000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "df_aguerd", nombre: "Nayef Aguerd", posicion: "defensa", precio: 2800000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "df_riad", nombre: "Chadi Riad", posicion: "defensa", precio: 2000000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "df_diop", nombre: "Issa Diop", posicion: "defensa", precio: 2200000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "df_salaheddine", nombre: "Anass Salah-Eddine", posicion: "defensa", precio: 1500000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "df_belammari", nombre: "Youssef Belammari", posicion: "defensa", precio: 1000000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "df_halhal", nombre: "Redouane Halhal", posicion: "defensa", precio: 800000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "df_elouahdi", nombre: "Zakaria El Ouahdi", posicion: "defensa", precio: 1600000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "mf_amrabat", nombre: "Sofyan Amrabat", posicion: "mediocampista", precio: 2800000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "mf_ounahi", nombre: "Azzedine Ounahi", posicion: "mediocampista", precio: 2500000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "mf_elkhannouss", nombre: "Bilal El Khannouss", posicion: "mediocampista", precio: 2600000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "mf_saibari", nombre: "Ismael Saibari", posicion: "mediocampista", precio: 2200000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "mf_elaynaoui", nombre: "Neil El Aynaoui", posicion: "mediocampista", precio: 1800000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "mf_bouaddi", nombre: "Ayyoub Bouaddi", posicion: "mediocampista", precio: 1200000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "mf_elmourabet", nombre: "Samir El Mourabet", posicion: "mediocampista", precio: 900000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "fw_brahim", nombre: "Brahim Díaz", posicion: "delantero", precio: 5500000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "fw_elkaabi", nombre: "Ayoub El Kaabi", posicion: "delantero", precio: 2800000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "fw_rahimi", nombre: "Soufiane Rahimi", posicion: "delantero", precio: 2500000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "fw_ezzalzouli", nombre: "Abdessamad Ezzalzouli", posicion: "delantero", precio: 2400000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "fw_talbi", nombre: "Chemsdine Talbi", posicion: "delantero", precio: 1200000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "fw_gessime", nombre: "Yassine Gessime", posicion: "delantero", precio: 900000, pais: "Marruecos", flag: "🇲🇦" },
  { id: "fw_amaimouni", nombre: "Ayoub Amaimouni-Echghouyabe", posicion: "delantero", precio: 800000, pais: "Marruecos", flag: "🇲🇦" },

  // --- MÉXICO ---
  { id: "gk_ochoa", nombre: "Guillermo Ochoa", posicion: "portero", precio: 1000000, pais: "México", flag: "🇲🇽" },

  // --- PAÍSES BAJOS ---
  { id: "gk_verbruggen", nombre: "Bart Verbruggen", posicion: "portero", precio: 3000000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "gk_flekken", nombre: "Mark Flekken", posicion: "portero", precio: 2500000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "gk_roefs", nombre: "Robin Roefs", posicion: "portero", precio: 1200000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "df_vandijk", nombre: "Virgil van Dijk", posicion: "defensa", precio: 5000000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "df_dumfries", nombre: "Denzel Dumfries", posicion: "defensa", precio: 3800000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "df_ake", nombre: "Nathan Aké", posicion: "defensa", precio: 4000000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "df_jtimber", nombre: "Jurriën Timber", posicion: "defensa", precio: 3500000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "df_vandeven", nombre: "Micky van de Ven", posicion: "defensa", precio: 4500000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "df_hato", nombre: "Jorrel Hato", posicion: "defensa", precio: 2800000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "df_vanhecke", nombre: "Jan Paul van Hecke", posicion: "defensa", precio: 2400000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "df_wieffer", nombre: "Mats Wieffer", posicion: "defensa", precio: 2600000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "mf_dejong", nombre: "Frenkie de Jong", posicion: "mediocampista", precio: 5500000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "mf_gravenberch", nombre: "Ryan Gravenberch", posicion: "mediocampista", precio: 4200000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "mf_reijnders", nombre: "Tijjani Reijnders", posicion: "mediocampista", precio: 4800000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "mf_koopmeiners", nombre: "Teun Koopmeiners", posicion: "mediocampista", precio: 4500000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "mf_deroon", nombre: "Marten de Roon", posicion: "mediocampista", precio: 1500000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "mf_qtimber", nombre: "Quinten Timber", posicion: "mediocampista", precio: 2500000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "mf_til", nombre: "Guus Til", posicion: "mediocampista", precio: 2000000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "fw_depay", nombre: "Memphis Depay", posicion: "delantero", precio: 3500000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "fw_gakpo", nombre: "Cody Gakpo", posicion: "delantero", precio: 5500000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "fw_malen", nombre: "Donyell Malen", posicion: "delantero", precio: 3800000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "fw_jkluivert", nombre: "Justin Kluivert", posicion: "delantero", precio: 2600000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "fw_brobbey", nombre: "Brian Brobbey", posicion: "delantero", precio: 2200000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "fw_lang", nombre: "Noa Lang", posicion: "delantero", precio: 2400000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "fw_summerville", nombre: "Crysencio Summerville", posicion: "delantero", precio: 3200000, pais: "Países Bajos", flag: "🇳🇱" },
  { id: "fw_weghorst", nombre: "Wout Weghorst", posicion: "delantero", precio: 1800000, pais: "Países Bajos", flag: "🇳🇱" },

  // --- ESTADOS UNIDOS ---
  { id: "gk_turner", nombre: "Matt Turner", posicion: "portero", precio: 2000000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "gk_freese", nombre: "Matt Freese", posicion: "portero", precio: 1000000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "gk_brady", nombre: "Chris Brady", posicion: "portero", precio: 800000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "df_dest", nombre: "Sergiño Dest", posicion: "defensa", precio: 2500000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "df_arobinson", nombre: "Antonee Robinson", posicion: "defensa", precio: 3000000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "df_richards", nombre: "Chris Richards", posicion: "defensa", precio: 2200000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "df_ream", nombre: "Tim Ream", posicion: "defensa", precio: 800000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "df_mckenzie", nombre: "Mark McKenzie", posicion: "defensa", precio: 1500000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "df_mrobinson", nombre: "Miles Robinson", posicion: "defensa", precio: 1400000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "df_scally", nombre: "Joe Scally", posicion: "defensa", precio: 1800000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "df_trusty", nombre: "Auston Trusty", posicion: "defensa", precio: 1600000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "df_freeman", nombre: "Alex Freeman", posicion: "defensa", precio: 700000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "df_arfsten", nombre: "Max Arfsten", posicion: "defensa", precio: 900000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "mf_adams", nombre: "Tyler Adams", posicion: "mediocampista", precio: 3000000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "mf_mckennie", nombre: "Weston McKennie", posicion: "mediocampista", precio: 3500000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "mf_reyna", nombre: "Gio Reyna", posicion: "mediocampista", precio: 2800000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "mf_tillman", nombre: "Malik Tillman", posicion: "mediocampista", precio: 3200000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "mf_roldan", nombre: "Cristian Roldan", posicion: "mediocampista", precio: 1200000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "mf_berhalter", nombre: "Sebastian Berhalter", posicion: "mediocampista", precio: 800000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "fw_pulisic", nombre: "Christian Pulisic", posicion: "delantero", precio: 5500000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "fw_weah", nombre: "Tim Weah", posicion: "delantero", precio: 2500000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "fw_balogun", nombre: "Folarin Balogun", posicion: "delantero", precio: 3500000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "fw_pepi", nombre: "Ricardo Pepi", posicion: "delantero", precio: 2200000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "fw_aaronson", nombre: "Brenden Aaronson", posicion: "delantero", precio: 1800000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "fw_wright", nombre: "Haji Wright", posicion: "delantero", precio: 1600000, pais: "Estados Unidos", flag: "🇺🇸" },
  { id: "fw_zendejas", nombre: "Alex Zendejas", posicion: "delantero", precio: 1500000, pais: "Estados Unidos", flag: "🇺🇸" },

  // --- COLOMBIA ---
  { id: "gk_vargas", nombre: "Camilo Vargas", posicion: "portero", precio: 1500000, pais: "Colombia", flag: "🇨🇴" },
  { id: "gk_ospina", nombre: "David Ospina", posicion: "portero", precio: 1000000, pais: "Colombia", flag: "🇨🇴" },
  { id: "gk_montero", nombre: "Álvaro Montero", posicion: "portero", precio: 1200000, pais: "Colombia", flag: "🇨🇴" },
  { id: "df_munoz", nombre: "Daniel Muñoz", posicion: "defensa", precio: 3200000, pais: "Colombia", flag: "🇨🇴" },
  { id: "df_sarias", nombre: "Santiago Arias", posicion: "defensa", precio: 1200000, pais: "Colombia", flag: "🇨🇴" },
  { id: "df_mina", nombre: "Yerry Mina", posicion: "defensa", precio: 1800000, pais: "Colombia", flag: "🇨🇴" },
  { id: "df_dsanchez", nombre: "Davinson Sánchez", posicion: "defensa", precio: 2800000, pais: "Colombia", flag: "🇨🇴" },
  { id: "df_lucumi", nombre: "Jhon Lucumí", posicion: "defensa", precio: 2500000, pais: "Colombia", flag: "🇨🇴" },
  { id: "df_ditta", nombre: "Willer Ditta", posicion: "defensa", precio: 1500000, pais: "Colombia", flag: "🇨🇴" },
  { id: "df_mojica", nombre: "Yohan Mojica", posicion: "defensa", precio: 1600000, pais: "Colombia", flag: "🇨🇴" },
  { id: "df_machado", nombre: "Déiver Machado", posicion: "defensa", precio: 1400000, pais: "Colombia", flag: "🇨🇴" },
  { id: "mf_james", nombre: "James Rodríguez", posicion: "mediocampista", precio: 4000000, pais: "Colombia", flag: "🇨🇴" },
  { id: "mf_lerma", nombre: "Jefferson Lerma", posicion: "mediocampista", precio: 3000000, pais: "Colombia", flag: "🇨🇴" },
  { id: "mf_rios", nombre: "Richard Ríos", posicion: "mediocampista", precio: 2800000, pais: "Colombia", flag: "🇨🇴" },
  { id: "mf_castano", nombre: "Kevin Castaño", posicion: "mediocampista", precio: 2000000, pais: "Colombia", flag: "🇨🇴" },
  { id: "mf_quintero", nombre: "Juan Fernando Quintero", posicion: "mediocampista", precio: 2200000, pais: "Colombia", flag: "🇨🇴" },
  { id: "mf_carrascal", nombre: "Jorge Carrascal", posicion: "mediocampista", precio: 1800000, pais: "Colombia", flag: "🇨🇴" },
  { id: "mf_puerta", nombre: "Gustavo Puerta", posicion: "mediocampista", precio: 1200000, pais: "Colombia", flag: "🇨🇴" },
  { id: "mf_portilla", nombre: "Juan Camilo Portilla", posicion: "mediocampista", precio: 1400000, pais: "Colombia", flag: "🇨🇴" },
  { id: "mf_jarias", nombre: "Jhon Arias", posicion: "mediocampista", precio: 2600000, pais: "Colombia", flag: "🇨🇴" },
  { id: "fw_luisdiaz", nombre: "Luis Díaz", posicion: "delantero", precio: 7000000, pais: "Colombia", flag: "🇨🇴" },
  { id: "fw_suarez", nombre: "Luis Suárez", posicion: "delantero", precio: 3000000, pais: "Colombia", flag: "🇨🇴" },
  { id: "fw_cucho", nombre: "Juan Camilo Hernández", posicion: "delantero", precio: 2800000, pais: "Colombia", flag: "🇨🇴" },
  { id: "fw_cordoba", nombre: "Jhon Córdoba", posicion: "delantero", precio: 2500000, pais: "Colombia", flag: "🇨🇴" },
  { id: "fw_gomez", nombre: "Carlos Andrés Gómez", posicion: "delantero", precio: 1800000, pais: "Colombia", flag: "🇨🇴" },
  { id: "fw_campaz", nombre: "Jaminton Campaz", posicion: "delantero", precio: 1600000, pais: "Colombia", flag: "🇨🇴" },

  // --- BRASIL ---
  { id: "gk_alisson", nombre: "Alisson Becker", posicion: "portero", precio: 4500000, pais: "Brasil", flag: "🇧🇷" },
  { id: "gk_ederson", nombre: "Ederson", posicion: "portero", precio: 4000000, pais: "Brasil", flag: "🇧🇷" },
  { id: "gk_weverton", nombre: "Weverton", posicion: "portero", precio: 1500000, pais: "Brasil", flag: "🇧🇷" },
  { id: "df_danilo", nombre: "Danilo", posicion: "defensa", precio: 2000000, pais: "Brasil", flag: "🇧🇷" },
  { id: "df_gabriel", nombre: "Gabriel Magalhaes", posicion: "defensa", precio: 4800000, pais: "Brasil", flag: "🇧🇷" },
  { id: "df_marquinhos", nombre: "Marquinhos", posicion: "defensa", precio: 4500000, pais: "Brasil", flag: "🇧🇷" },
  { id: "df_alexsandro", nombre: "Alex Sandro", posicion: "defensa", precio: 1800000, pais: "Brasil", flag: "🇧🇷" },
  { id: "df_leopereira", nombre: "Leo Pereira", posicion: "defensa", precio: 2200000, pais: "Brasil", flag: "🇧🇷" },
  { id: "df_wesley", nombre: "Wesley", posicion: "defensa", precio: 2400000, pais: "Brasil", flag: "🇧🇷" },
  { id: "df_douglassantos", nombre: "Douglas Santos", posicion: "defensa", precio: 2000000, pais: "Brasil", flag: "🇧🇷" },
  { id: "df_bremer", nombre: "Bremer", posicion: "defensa", precio: 3800000, pais: "Brasil", flag: "🇧🇷" },
  { id: "df_ibanez", nombre: "Roger Ibanez", posicion: "defensa", precio: 3000000, pais: "Brasil", flag: "🇧🇷" },
  { id: "mf_casemiro", nombre: "Casemiro", posicion: "mediocampista", precio: 2500000, pais: "Brasil", flag: "🇧🇷" },
  { id: "mf_guimaraes", nombre: "Bruno Guimaraes", posicion: "mediocampista", precio: 5500000, pais: "Brasil", flag: "🇧🇷" },
  { id: "mf_fabinho", nombre: "Fabinho", posicion: "mediocampista", precio: 2200000, pais: "Brasil", flag: "🇧🇷" },
  { id: "mf_paqueta", nombre: "Lucas Paqueta", posicion: "mediocampista", precio: 3800000, pais: "Brasil", flag: "🇧🇷" },
  { id: "mf_danilosantos", nombre: "Danilo Santos", posicion: "mediocampista", precio: 3000000, pais: "Brasil", flag: "🇧🇷" },
  { id: "fw_vinicius", nombre: "Vinicius Junior", posicion: "delantero", precio: 11000000, pais: "Brasil", flag: "🇧🇷" },
  { id: "fw_cunha", nombre: "Matheus Cunha", posicion: "delantero", precio: 3500000, pais: "Brasil", flag: "🇧🇷" },
  { id: "fw_neymar", nombre: "Neymar", posicion: "delantero", precio: 6000000, pais: "Brasil", flag: "🇧🇷" },
  { id: "fw_raphinha", nombre: "Raphinha", posicion: "delantero", precio: 6500000, pais: "Brasil", flag: "🇧🇷" },
  { id: "fw_rayan", nombre: "Rayan", posicion: "delantero", precio: 2000000, pais: "Brasil", flag: "🇧🇷" },
  { id: "fw_thiago", nombre: "Igor Thiago", posicion: "delantero", precio: 2400000, pais: "Brasil", flag: "🇧🇷" },
  { id: "fw_endrick", nombre: "Endrick", posicion: "delantero", precio: 4500000, pais: "Brasil", flag: "🇧🇷" },
  { id: "fw_luizhenrique", nombre: "Luiz Henrique", posicion: "delantero", precio: 3000000, pais: "Brasil", flag: "🇧🇷" },
  { id: "fw_martinelli", nombre: "Gabriel Martinelli", posicion: "delantero", precio: 4800000, pais: "Brasil", flag: "🇧🇷" },

  // --- CANADÁ ---
  { id: "gk_crepeau", nombre: "Maxime Crépeau", posicion: "portero", precio: 2000000, pais: "Canadá", flag: "🇨🇦" },
  { id: "gk_goodman", nombre: "Owen Goodman", posicion: "portero", precio: 1200000, pais: "Canadá", flag: "🇨🇦" },
  { id: "gk_stclair", nombre: "Dayne St. Clair", posicion: "portero", precio: 1800000, pais: "Canadá", flag: "🇨🇦" },
  { id: "df_bombito", nombre: "Moise Bombito", posicion: "defensa", precio: 2500000, pais: "Canadá", flag: "🇨🇦" },
  { id: "df_cornelius", nombre: "Derek Cornelius", posicion: "defensa", precio: 1800000, pais: "Canadá", flag: "🇨🇦" },
  { id: "df_davies", nombre: "Alphonso Davies", posicion: "defensa", precio: 4500000, pais: "Canadá", flag: "🇨🇦" },
  { id: "df_fougerolles", nombre: "Luc de Fougerolles", posicion: "defensa", precio: 1500000, pais: "Canadá", flag: "🇨🇦" },
  { id: "df_johnson", nombre: "Alistair Johnson", posicion: "defensa", precio: 2200000, pais: "Canadá", flag: "🇨🇦" },
  { id: "df_jones", nombre: "Alfie Jones", posicion: "defensa", precio: 1600000, pais: "Canadá", flag: "🇨🇦" },
  { id: "df_laryea", nombre: "Richie Laryea", posicion: "defensa", precio: 1500000, pais: "Canadá", flag: "🇨🇦" },
  { id: "df_sigur", nombre: "Niko Sigur", posicion: "defensa", precio: 1800000, pais: "Canadá", flag: "🇨🇦" },
  { id: "df_waterman", nombre: "Joel Waterman", posicion: "defensa", precio: 1400000, pais: "Canadá", flag: "🇨🇦" },
  { id: "mf_ahmed", nombre: "Ali Ahmed", posicion: "mediocampista", precio: 1600000, pais: "Canadá", flag: "🇨🇦" },
  { id: "mf_buchanan", nombre: "Tajon Buchanan", posicion: "mediocampista", precio: 2800000, pais: "Canadá", flag: "🇨🇦" },
  { id: "mf_choiniere", nombre: "Mathieu Choiniere", posicion: "mediocampista", precio: 1800000, pais: "Canadá", flag: "🇨🇦" },
  { id: "mf_eustaquio", nombre: "Stephen Eustaquio", posicion: "mediocampista", precio: 3000000, pais: "Canadá", flag: "🇨🇦" },
  { id: "mf_flores", nombre: "Marcelo Flores", posicion: "mediocampista", precio: 2000000, pais: "Canadá", flag: "🇨🇦" },
  { id: "mf_kone", nombre: "Ismael Kone", posicion: "mediocampista", precio: 2400000, pais: "Canadá", flag: "🇨🇦" },
  { id: "mf_millar", nombre: "Liam Millar", posicion: "mediocampista", precio: 1800000, pais: "Canadá", flag: "🇨🇦" },
  { id: "mf_saliba", nombre: "Nathan Saliba", posicion: "mediocampista", precio: 1500000, pais: "Canadá", flag: "🇨🇦" },
  { id: "mf_osorio", nombre: "Jonathan Osorio", posicion: "mediocampista", precio: 1700000, pais: "Canadá", flag: "🇨🇦" },
  { id: "mf_shaffelburg", nombre: "Jacob Shaffelburg", posicion: "mediocampista", precio: 2200000, pais: "Canadá", flag: "🇨🇦" },
  { id: "fw_david", nombre: "Jonathan David", posicion: "delantero", precio: 5000000, pais: "Canadá", flag: "🇨🇦" },
  { id: "fw_promisedavid", nombre: "Promise David", posicion: "delantero", precio: 1600000, pais: "Canadá", flag: "🇨🇦" },
  { id: "fw_larin", nombre: "Cyle Larin", posicion: "delantero", precio: 2600000, pais: "Canadá", flag: "🇨🇦" },
  { id: "fw_oluwaseyi", nombre: "Tani Oluwaseyi", posicion: "delantero", precio: 2000000, pais: "Canadá", flag: "🇨🇦" },

  // --- COREA DEL SUR ---
  { id: "gk_hyeonwoo", nombre: "Jo Hyeon-woo", posicion: "portero", precio: 1800000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "gk_seunggyu", nombre: "Kim Seung-gyu", posicion: "portero", precio: 1500000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "gk_bumkeun", nombre: "Song Bum-keun", posicion: "portero", precio: 1000000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "df_kim", nombre: "Kim Min-jae", posicion: "defensa", precio: 4000000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "df_yumin", nombre: "Cho Yu-min", posicion: "defensa", precio: 1500000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "df_hanbeom", nombre: "Lee Han-beom", posicion: "defensa", precio: 1400000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "df_taehyeon", nombre: "Kim Tae-hyeon", posicion: "defensa", precio: 1200000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "df_jinseob", nombre: "Park Jin-seob", posicion: "defensa", precio: 1400000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "df_gihyuk", nombre: "Lee Gi-hyuk", posicion: "defensa", precio: 1000000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "df_taeseok", nombre: "Lee Tae-seok", posicion: "defensa", precio: 1200000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "df_youngwoo", nombre: "Seol Young-woo", posicion: "defensa", precio: 1800000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "df_castrop", nombre: "Jens Castrop", posicion: "defensa", precio: 2000000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "df_moonhwan", nombre: "Kim Moon-hwan", posicion: "defensa", precio: 1200000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "mf_hyunjun", nombre: "Yang Hyun-jun", posicion: "mediocampista", precio: 2000000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "mf_seungho", nombre: "Paik Seung-ho", posicion: "mediocampista", precio: 1800000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "mf_inbeom", nombre: "Hwang In-beom", posicion: "mediocampista", precio: 2500000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "mf_jingyu", nombre: "Kim Jin-gyu", posicion: "mediocampista", precio: 1200000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "mf_junho", nombre: "Bae Jun-ho", posicion: "mediocampista", precio: 2200000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "mf_jisung", nombre: "Eom Ji-sung", posicion: "mediocampista", precio: 1800000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "mf_heechan", nombre: "Hwang Hee-chan", posicion: "mediocampista", precio: 3200000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "mf_donggyeong", nombre: "Lee Dong-gyeong", posicion: "mediocampista", precio: 1500000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "mf_jaesung", nombre: "Lee Jae-sung", posicion: "mediocampista", precio: 2200000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "mf_kangin", nombre: "Lee Kang-in", posicion: "mediocampista", precio: 4500000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "fw_hyeongyu", nombre: "Oh Hyeon-gyu", posicion: "delantero", precio: 2000000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "fw_son", nombre: "Heung-min Son", posicion: "delantero", precio: 5500000, pais: "Corea del Sur", flag: "🇰🇷" },
  { id: "fw_guesung", nombre: "Cho Gue-sung", posicion: "delantero", precio: 2200000, pais: "Corea del Sur", flag: "🇰🇷" },

  // --- BÉLGICA ---
  { id: "gk_courtois", nombre: "Thibaut Courtois", posicion: "portero", precio: 4500000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "gk_lammens", nombre: "Senne Lammens", posicion: "portero", precio: 1800000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "gk_penders", nombre: "Mike Penders", posicion: "portero", precio: 1500000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "df_castagne", nombre: "Timothy Castagne", posicion: "defensa", precio: 2600000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "df_debast", nombre: "Zeno Debast", posicion: "defensa", precio: 3000000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "df_decuyper", nombre: "Maxim De Cuyper", posicion: "defensa", precio: 2800000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "df_dewinter", nombre: "Koni De Winter", posicion: "defensa", precio: 2500000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "df_mechele", nombre: "Brandon Mechele", posicion: "defensa", precio: 1800000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "df_meunier", nombre: "Thomas Meunier", posicion: "defensa", precio: 2000000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "df_ngoy", nombre: "Nathan Ngoy", posicion: "defensa", precio: 1600000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "df_seys", nombre: "Joaquin Seys", posicion: "defensa", precio: 1800000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "df_theate", nombre: "Arthur Theate", posicion: "defensa", precio: 3200000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "mf_debruyne", nombre: "Kevin De Bruyne", posicion: "mediocampista", precio: 7500000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "mf_aonana", nombre: "Amadou Onana", posicion: "mediocampista", precio: 4000000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "mf_raskin", nombre: "Nicolas Raskin", posicion: "mediocampista", precio: 2200000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "mf_tielemans", nombre: "Youri Tielemans", posicion: "mediocampista", precio: 3800000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "mf_vanaken", nombre: "Hans Vanaken", posicion: "mediocampista", precio: 2500000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "mf_witsel", nombre: "Axel Witsel", posicion: "mediocampista", precio: 1800000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "fw_deketelaere", nombre: "Charles De Ketelaere", posicion: "delantero", precio: 4500000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "fw_doku", nombre: "Jérémy Doku", posicion: "delantero", precio: 5500000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "fw_fernandezpardo", nombre: "Matias Fernandez-Pardo", posicion: "delantero", precio: 2200000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "fw_lukaku", nombre: "Romelu Lukaku", posicion: "delantero", precio: 5000000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "fw_lukebakio", nombre: "Dodi Lukebakio", posicion: "delantero", precio: 3500000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "fw_dmoreira", nombre: "Diego Moreira", posicion: "delantero", precio: 2400000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "fw_saelemaekers", nombre: "Alexis Saelemaekers", posicion: "delantero", precio: 2800000, pais: "Bélgica", flag: "🇧🇪" },
  { id: "fw_trossard", nombre: "Leandro Trossard", posicion: "delantero", precio: 5000000, pais: "Bélgica", flag: "🇧🇪" },

  // --- PORTUGAL ---
  { id: "mf_fernandes", nombre: "Bruno Fernandes", posicion: "mediocampista", precio: 6200000, pais: "Portugal", flag: "🇵🇹" },
  { id: "fw_ronaldo", nombre: "Cristiano Ronaldo", posicion: "delantero", precio: 5500000, pais: "Portugal", flag: "🇵🇹" },

  // --- URUGUAY ---
  { id: "mf_valverde", nombre: "Federico Valverde", posicion: "mediocampista", precio: 7500000, pais: "Uruguay", flag: "🇺🇾" },

  // --- NORUEGA ---
  { id: "gk_nyland", nombre: "Ørjan Nyland", posicion: "portero", precio: 1500000, pais: "Noruega", flag: "🇳🇴" },
  { id: "gk_selvik", nombre: "Egil Selvik", posicion: "portero", precio: 1000000, pais: "Noruega", flag: "🇳🇴" },
  { id: "gk_tangvik", nombre: "Sander Tangvik", posicion: "portero", precio: 800000, pais: "Noruega", flag: "🇳🇴" },
  { id: "df_ajer", nombre: "Kristoffer Ajer", posicion: "defensa", precio: 2500000, pais: "Noruega", flag: "🇳🇴" },
  { id: "df_ryerson", nombre: "Julian Ryerson", posicion: "defensa", precio: 2800000, pais: "Noruega", flag: "🇳🇴" },
  { id: "df_ostigard", nombre: "Leo Østigård", posicion: "defensa", precio: 2000000, pais: "Noruega", flag: "🇳🇴" },
  { id: "df_mollerwolfe", nombre: "David Møller Wolfe", posicion: "defensa", precio: 1800000, pais: "Noruega", flag: "🇳🇴" },
  { id: "df_pedersen", nombre: "Marcus Holmgren Pedersen", posicion: "defensa", precio: 1600000, pais: "Noruega", flag: "🇳🇴" },
  { id: "df_heggem", nombre: "Torbjørn Heggem", posicion: "defensa", precio: 1400000, pais: "Noruega", flag: "🇳🇴" },
  { id: "df_bjorkan", nombre: "Fredrik Bjørkan", posicion: "defensa", precio: 1200000, pais: "Noruega", flag: "🇳🇴" },
  { id: "df_falchener", nombre: "Henrik Falchener", posicion: "defensa", precio: 800000, pais: "Noruega", flag: "🇳🇴" },
  { id: "df_langas", nombre: "Sondre Langås", posicion: "defensa", precio: 1000000, pais: "Noruega", flag: "🇳🇴" },
  { id: "mf_odegaard", nombre: "Martin Ødegaard", posicion: "mediocampista", precio: 8500000, pais: "Noruega", flag: "🇳🇴" },
  { id: "mf_berge", nombre: "Sander Berge", posicion: "mediocampista", precio: 3000000, pais: "Noruega", flag: "🇳🇴" },
  { id: "mf_pberg", nombre: "Patrick Berg", posicion: "mediocampista", precio: 1800000, pais: "Noruega", flag: "🇳🇴" },
  { id: "mf_thorstvedt", nombre: "Kristian Thorstvedt", posicion: "mediocampista", precio: 2200000, pais: "Noruega", flag: "🇳🇴" },
  { id: "mf_thorsby", nombre: "Morten Thorsby", posicion: "mediocampista", precio: 1500000, pais: "Noruega", flag: "🇳🇴" },
  { id: "mf_aasgaard", nombre: "Thelo Aasgaard", posicion: "mediocampista", precio: 1400000, pais: "Noruega", flag: "🇳🇴" },
  { id: "mf_aursnes", nombre: "Fredrik Aursnes", posicion: "mediocampista", precio: 3200000, pais: "Noruega", flag: "🇳🇴" },
  { id: "mf_schjelderup", nombre: "Andreas Schjelderup", posicion: "mediocampista", precio: 2400000, pais: "Noruega", flag: "🇳🇴" },
  { id: "mf_hauge", nombre: "Jens Petter Hauge", posicion: "mediocampista", precio: 2000000, pais: "Noruega", flag: "🇳🇴" },
  { id: "fw_haaland", nombre: "Erling Haaland", posicion: "delantero", precio: 11500000, pais: "Noruega", flag: "🇳🇴" },
  { id: "fw_sorloth", nombre: "Alexander Sørloth", posicion: "delantero", precio: 4000000, pais: "Noruega", flag: "🇳🇴" },
  { id: "fw_strandlarsen", nombre: "Jørgen Strand Larsen", posicion: "delantero", precio: 3200000, pais: "Noruega", flag: "🇳🇴" },
  { id: "fw_nusa", nombre: "Antonio Nusa", posicion: "delantero", precio: 3500000, pais: "Noruega", flag: "🇳🇴" },
  { id: "fw_bobb", nombre: "Oscar Bobb", posicion: "delantero", precio: 3000000, pais: "Noruega", flag: "🇳🇴" },

  // --- SUIZA ---
  { id: "gk_kobel", nombre: "Gregor Kobel", posicion: "portero", precio: 4000000, pais: "Suiza", flag: "🇨🇭" },
  { id: "gk_mvogo", nombre: "Yvon Mvogo", posicion: "portero", precio: 1800000, pais: "Suiza", flag: "🇨🇭" },
  { id: "gk_keller", nombre: "Marvin Keller", posicion: "portero", precio: 1200000, pais: "Suiza", flag: "🇨🇭" },
  { id: "df_akanji", nombre: "Manuel Akanji", posicion: "defensa", precio: 4200000, pais: "Suiza", flag: "🇨🇭" },
  { id: "df_rrodriguez", nombre: "Ricardo Rodríguez", posicion: "defensa", precio: 2000000, pais: "Suiza", flag: "🇨🇭" },
  { id: "df_elvedi", nombre: "Nico Elvedi", posicion: "defensa", precio: 2500000, pais: "Suiza", flag: "🇨🇭" },
  { id: "df_widmer", nombre: "Silvan Widmer", posicion: "defensa", precio: 1800000, pais: "Suiza", flag: "🇨🇭" },
  { id: "df_muheim", nombre: "Miro Muheim", posicion: "defensa", precio: 1600000, pais: "Suiza", flag: "🇨🇭" },
  { id: "df_comert", nombre: "Eray Cömert", posicion: "defensa", precio: 2000000, pais: "Suiza", flag: "🇨🇭" },
  { id: "df_jaquez", nombre: "Luca Jaquez", posicion: "defensa", precio: 1500000, pais: "Suiza", flag: "🇨🇭" },
  { id: "df_amenda", nombre: "Aurèle Amenda", posicion: "defensa", precio: 1800000, pais: "Suiza", flag: "🇨🇭" },
  { id: "mf_xhaka", nombre: "Granit Xhaka", posicion: "mediocampista", precio: 4500000, pais: "Suiza", flag: "🇨🇭" },
  { id: "mf_freuler", nombre: "Remo Freuler", posicion: "mediocampista", precio: 2800000, pais: "Suiza", flag: "🇨🇭" },
  { id: "mf_aebischer", nombre: "Michel Aebischer", posicion: "mediocampista", precio: 2200000, pais: "Suiza", flag: "🇨🇭" },
  { id: "mf_zakaria", nombre: "Denis Zakaria", posicion: "mediocampista", precio: 3500000, pais: "Suiza", flag: "🇨🇭" },
  { id: "mf_sow", nombre: "Djibril Sow", posicion: "mediocampista", precio: 2600000, pais: "Suiza", flag: "🇨🇭" },
  { id: "mf_rieder", nombre: "Fabian Rieder", posicion: "mediocampista", precio: 2400000, pais: "Suiza", flag: "🇨🇭" },
  { id: "mf_jashari", nombre: "Ardon Jashari", posicion: "mediocampista", precio: 2000000, pais: "Suiza", flag: "🇨🇭" },
  { id: "mf_fassnacht", nombre: "Christian Fassnacht", posicion: "mediocampista", precio: 1500000, pais: "Suiza", flag: "🇨🇭" },
  { id: "mf_manzambi", nombre: "Johan Manzambi", posicion: "mediocampista", precio: 1200000, pais: "Suiza", flag: "🇨🇭" },
  { id: "fw_embolo", nombre: "Breel Embolo", posicion: "delantero", precio: 3000000, pais: "Suiza", flag: "🇨🇭" },
  { id: "fw_ndoye", nombre: "Dan Ndoye", posicion: "delantero", precio: 3200000, pais: "Suiza", flag: "🇨🇭" },
  { id: "fw_rvargas", nombre: "Ruben Vargas", posicion: "delantero", precio: 2800000, pais: "Suiza", flag: "🇨🇭" },
  { id: "fw_amdouni", nombre: "Zeki Amdouni", posicion: "delantero", precio: 2500000, pais: "Suiza", flag: "🇨🇭" },
  { id: "fw_okafor", nombre: "Noah Okafor", posicion: "delantero", precio: 2800000, pais: "Suiza", flag: "🇨🇭" },
  { id: "fw_itten", nombre: "Cedric Itten", posicion: "delantero", precio: 1800000, pais: "Suiza", flag: "🇨🇭" },

  // --- ESCOCIA ---
  { id: "gk_cgordon", nombre: "Craig Gordon", posicion: "portero", precio: 1000000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "gk_gunn", nombre: "Angus Gunn", posicion: "portero", precio: 2000000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "gk_lkelly", nombre: "Liam Kelly", posicion: "portero", precio: 1200000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "df_hanley", nombre: "Grant Hanley", posicion: "defensa", precio: 1200000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "df_hendry", nombre: "Jack Hendry", posicion: "defensa", precio: 1800000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "df_hickey", nombre: "Aaron Hickey", posicion: "defensa", precio: 2500000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "df_hyam", nombre: "Dom Hyam", posicion: "defensa", precio: 1400000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "df_mckenna", nombre: "Scott McKenna", posicion: "defensa", precio: 1600000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "df_patterson", nombre: "Nathan Patterson", posicion: "defensa", precio: 2000000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "df_ralston", nombre: "Anthony Ralston", posicion: "defensa", precio: 1500000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "df_robertson", nombre: "Andy Robertson", posicion: "defensa", precio: 4500000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "df_souttar", nombre: "John Souttar", posicion: "defensa", precio: 1800000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "df_tierney", nombre: "Kieran Tierney", posicion: "defensa", precio: 3000000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "mf_christie", nombre: "Ryan Christie", posicion: "mediocampista", precio: 2500000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "mf_curtis", nombre: "Findlay Curtis", posicion: "mediocampista", precio: 1000000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "mf_ferguson", nombre: "Lewis Ferguson", posicion: "mediocampista", precio: 2800000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "mf_doak", nombre: "Ben Gannon-Doak", posicion: "mediocampista", precio: 2200000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "mf_gilmour", nombre: "Billy Gilmour", posicion: "mediocampista", precio: 3200000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "mf_mcginn", nombre: "John McGinn", posicion: "mediocampista", precio: 3800000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "mf_mclean", nombre: "Kenny McLean", posicion: "mediocampista", precio: 1600000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "mf_mctominay", nombre: "Scott McTominay", posicion: "mediocampista", precio: 3500000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "fw_cadams", nombre: "Che Adams", posicion: "delantero", precio: 2600000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "fw_dykes", nombre: "Lyndon Dykes", posicion: "delantero", precio: 1600000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "fw_hirst", nombre: "George Hirst", posicion: "delantero", precio: 1800000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "fw_shankland", nombre: "Lawrence Shankland", posicion: "delantero", precio: 2000000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "fw_rstewart", nombre: "Ross Stewart", posicion: "delantero", precio: 1500000, pais: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },

  // --- AUSTRIA ---
  { id: "gk_pentz", nombre: "Patrick Pentz", posicion: "portero", precio: 1500000, pais: "Austria", flag: "🇦🇹" },
  { id: "gk_aschlager", nombre: "Alexander Schlager", posicion: "portero", precio: 1800000, pais: "Austria", flag: "🇦🇹" },
  { id: "gk_wiegele", nombre: "Florian Wiegele", posicion: "portero", precio: 1000000, pais: "Austria", flag: "🇦🇹" },
  { id: "df_affengruber", nombre: "David Affengruber", posicion: "defensa", precio: 1800000, pais: "Austria", flag: "🇦🇹" },
  { id: "df_alaba", nombre: "David Alaba", posicion: "defensa", precio: 4000000, pais: "Austria", flag: "🇦🇹" },
  { id: "df_danso", nombre: "Kevin Danso", posicion: "defensa", precio: 3200000, pais: "Austria", flag: "🇦🇹" },
  { id: "df_friedl", nombre: "Marco Friedl", posicion: "defensa", precio: 2200000, pais: "Austria", flag: "🇦🇹" },
  { id: "df_lienhart", nombre: "Philipp Lienhart", posicion: "defensa", precio: 2500000, pais: "Austria", flag: "🇦🇹" },
  { id: "df_mwene", nombre: "Phillipp Mwene", posicion: "defensa", precio: 1600000, pais: "Austria", flag: "🇦🇹" },
  { id: "df_posch", nombre: "Stefan Posch", posicion: "defensa", precio: 2600000, pais: "Austria", flag: "🇦🇹" },
  { id: "df_prass", nombre: "Alexander Prass", posicion: "defensa", precio: 2000000, pais: "Austria", flag: "🇦🇹" },
  { id: "df_svoboda", nombre: "Michael Svoboda", posicion: "defensa", precio: 1400000, pais: "Austria", flag: "🇦🇹" },
  { id: "mf_baumgartner", nombre: "Christoph Baumgartner", posicion: "mediocampista", precio: 3500000, pais: "Austria", flag: "🇦🇹" },
  { id: "mf_chukwuemeka", nombre: "Carney Chukwuemeka", posicion: "mediocampista", precio: 2500000, pais: "Austria", flag: "🇦🇹" },
  { id: "mf_grillitsch", nombre: "Florian Grillitsch", posicion: "mediocampista", precio: 2200000, pais: "Austria", flag: "🇦🇹" },
  { id: "mf_laimer", nombre: "Konrad Laimer", posicion: "mediocampista", precio: 3500000, pais: "Austria", flag: "🇦🇹" },
  { id: "mf_sabitzer", nombre: "Marcel Sabitzer", posicion: "mediocampista", precio: 3800000, pais: "Austria", flag: "🇦🇹" },
  { id: "mf_xschlager", nombre: "Xaver Schlager", posicion: "mediocampista", precio: 3000000, pais: "Austria", flag: "🇦🇹" },
  { id: "mf_schmid", nombre: "Romano Schmid", posicion: "mediocampista", precio: 2000000, pais: "Austria", flag: "🇦🇹" },
  { id: "mf_schopf", nombre: "Alessandro Schopf", posicion: "mediocampista", precio: 1400000, pais: "Austria", flag: "🇦🇹" },
  { id: "mf_seiwald", nombre: "Nicolas Seiwald", posicion: "mediocampista", precio: 2400000, pais: "Austria", flag: "🇦🇹" },
  { id: "mf_wanner", nombre: "Paul Wanner", posicion: "mediocampista", precio: 2800000, pais: "Austria", flag: "🇦🇹" },
  { id: "mf_wimmer", nombre: "Patrick Wimmer", posicion: "mediocampista", precio: 2500000, pais: "Austria", flag: "🇦🇹" },
  { id: "fw_arnautovic", nombre: "Marko Arnautovic", posicion: "delantero", precio: 1800000, pais: "Austria", flag: "🇦🇹" },
  { id: "fw_gregoritsch", nombre: "Michael Gregoritsch", posicion: "delantero", precio: 2200000, pais: "Austria", flag: "🇦🇹" },
  { id: "fw_kalajdzic", nombre: "Sasa Kalajdzic", posicion: "delantero", precio: 2000000, pais: "Austria", flag: "🇦🇹" },

  // --- POLONIA ---
  { id: "fw_lewandowski", nombre: "R. Lewandowski", posicion: "delantero", precio: 4500000, pais: "Polonia", flag: "🇵🇱" },

  // --- EGIPTO ---
  { id: "fw_salah", nombre: "Mohamed Salah", posicion: "delantero", precio: 6800000, pais: "Egipto", flag: "🇪🇬" },

  // --- CABO VERDE ---
  { id: "gk_jdias", nombre: "Josimar Dias", posicion: "portero", precio: 1200000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "gk_marciodarosa", nombre: "Marcio da Rosa", posicion: "portero", precio: 1000000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "gk_csantos", nombre: "Carlos Santos", posicion: "portero", precio: 1200000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "df_moreira", nombre: "Steven Moreira", posicion: "defensa", precio: 1800000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "df_wpina", nombre: "Wagner Pina", posicion: "defensa", precio: 1600000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "df_jpfernandes", nombre: "Joao Paulo Fernandes", posicion: "defensa", precio: 1500000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "df_scabral", nombre: "Sidny Lopes Cabral", posicion: "defensa", precio: 1400000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "df_lcosta", nombre: "Logan Costa", posicion: "defensa", precio: 3200000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "df_rlopes", nombre: "Roberto Lopes", posicion: "defensa", precio: 1200000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "df_kpires", nombre: "Kelvin Pires", posicion: "defensa", precio: 1000000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "df_itavares", nombre: "Ianique Tavares", posicion: "defensa", precio: 1200000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "df_eborges", nombre: "Edilson Borges", posicion: "defensa", precio: 1400000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "mf_monteiro", nombre: "Jamiro Monteiro", posicion: "mediocampista", precio: 1800000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "mf_arcanjo", nombre: "Telmo Arcanjo", posicion: "mediocampista", precio: 1600000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "mf_ysemedo", nombre: "Yannick Semedo", posicion: "mediocampista", precio: 1500000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "mf_lduarte", nombre: "Laros Duarte", posicion: "mediocampista", precio: 1400000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "mf_dduarte", nombre: "Deroy Duarte", posicion: "mediocampista", precio: 1600000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "mf_kpina", nombre: "Kevin Pina", posicion: "mediocampista", precio: 1800000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "fw_rmendes", nombre: "Ryan Mendes", posicion: "delantero", precio: 2000000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "fw_wsemedo", nombre: "Willy Semedo", posicion: "delantero", precio: 1600000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "fw_grodrigues", nombre: "Garry Rodrigues", posicion: "delantero", precio: 1800000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "fw_jcabral", nombre: "Jovane Cabral", posicion: "delantero", precio: 2200000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "fw_dacosta", nombre: "Nuno da Costa", posicion: "delantero", precio: 1800000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "fw_dlivramento", nombre: "Dailon Livramento", posicion: "delantero", precio: 1600000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "fw_benchimol", nombre: "Gilson Benchimol", posicion: "delantero", precio: 1500000, pais: "Cabo Verde", flag: "🇨🇻" },
  { id: "fw_hvarela", nombre: "Helio Varela", posicion: "delantero", precio: 1600000, pais: "Cabo Verde", flag: "🇨🇻" },

  // --- CURAZAO ---
  { id: "gk_tbodak", nombre: "Tyrick Bodak", posicion: "portero", precio: 1000000, pais: "Curazao", flag: "🇨🇼" },
  { id: "gk_tdoornbusch", nombre: "Trevor Doornbusch", posicion: "portero", precio: 1200000, pais: "Curazao", flag: "🇨🇼" },
  { id: "gk_eroom", nombre: "Eloy Room", posicion: "portero", precio: 1600000, pais: "Curazao", flag: "🇨🇼" },
  { id: "df_bazoer", nombre: "Riechedly Bazoer", posicion: "defensa", precio: 2500000, pais: "Curazao", flag: "🇨🇼" },
  { id: "df_jbrenet", nombre: "Joshua Brenet", posicion: "defensa", precio: 2200000, pais: "Curazao", flag: "🇨🇼" },
  { id: "df_vaneijma", nombre: "Roshon van Eijma", posicion: "defensa", precio: 1500000, pais: "Curazao", flag: "🇨🇼" },
  { id: "df_sfloranus", nombre: "Sherel Floranus", posicion: "defensa", precio: 1800000, pais: "Curazao", flag: "🇨🇼" },
  { id: "df_dfonville", nombre: "Deveron Fonville", posicion: "defensa", precio: 1200000, pais: "Curazao", flag: "🇨🇼" },
  { id: "df_jgaari", nombre: "Jurien Gaari", posicion: "defensa", precio: 1400000, pais: "Curazao", flag: "🇨🇼" },
  { id: "df_aobispo", nombre: "Armando Obispo", posicion: "defensa", precio: 2800000, pais: "Curazao", flag: "🇨🇼" },
  { id: "df_ssambo", nombre: "Shurandy Sambo", posicion: "defensa", precio: 2000000, pais: "Curazao", flag: "🇨🇼" },
  { id: "mf_jbacuna", nombre: "Juninho Bacuna", posicion: "mediocampista", precio: 2200000, pais: "Curazao", flag: "🇨🇼" },
  { id: "mf_lbacuna", nombre: "Leandro Bacuna", posicion: "mediocampista", precio: 1800000, pais: "Curazao", flag: "🇨🇼" },
  { id: "mf_lcomenencia", nombre: "Livano Comenencia", posicion: "mediocampista", precio: 1600000, pais: "Curazao", flag: "🇨🇼" },
  { id: "mf_kfelida", nombre: "Kevin Felida", posicion: "mediocampista", precio: 1400000, pais: "Curazao", flag: "🇨🇼" },
  { id: "mf_amartha", nombre: "Ar'Jany Martha", posicion: "mediocampista", precio: 1500000, pais: "Curazao", flag: "🇨🇼" },
  { id: "mf_tnoslin", nombre: "Tyrese Noslin", posicion: "mediocampista", precio: 1200000, pais: "Curazao", flag: "🇨🇼" },
  { id: "mf_groemeratoe", nombre: "Godfried Roemeratoe", posicion: "mediocampista", precio: 1600000, pais: "Curazao", flag: "🇨🇼" },
  { id: "fw_jantonisse", nombre: "Jeremy Antonisse", posicion: "delantero", precio: 1500000, pais: "Curazao", flag: "🇨🇼" },
  { id: "fw_tchong", nombre: "Tahith Chong", posicion: "delantero", precio: 3500000, pais: "Curazao", flag: "🇨🇼" },
  { id: "fw_kgorre", nombre: "Kenji Gorre", posicion: "delantero", precio: 1800000, pais: "Curazao", flag: "🇨🇼" },
  { id: "fw_shansen", nombre: "Sontje Hansen", posicion: "delantero", precio: 2400000, pais: "Curazao", flag: "🇨🇼" },
  { id: "fw_gkastaneer", nombre: "Gervane Kastaneer", posicion: "delantero", precio: 1400000, pais: "Curazao", flag: "🇨🇼" },
  { id: "fw_bkuwas", nombre: "Brandley Kuwas", posicion: "delantero", precio: 1600000, pais: "Curazao", flag: "🇨🇼" },
  { id: "fw_jlocadia", nombre: "Jurgen Locadia", posicion: "delantero", precio: 2000000, pais: "Curazao", flag: "🇨🇼" },
  { id: "fw_jmargaritha", nombre: "Jearl Margaritha", posicion: "delantero", precio: 1500000, pais: "Curazao", flag: "🇨🇼" },

  // --- R.D. DEL CONGO ---
  { id: "gk_mepolo", nombre: "Matthieu Epolo", posicion: "portero", precio: 1400000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "gk_tfayulu", nombre: "Timothy Fayulu", posicion: "portero", precio: 1200000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "gk_lmpasi", nombre: "Lionel Mpasi", posicion: "portero", precio: 1800000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "df_cmbemba", nombre: "Chancel Mbemba", posicion: "defensa", precio: 3500000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "df_wanbissaka", nombre: "Aaron Wan-Bissaka", posicion: "defensa", precio: 3800000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "df_atuanzebe", nombre: "Axel Tuanzebe", posicion: "defensa", precio: 2400000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "df_amasuaku", nombre: "Arthur Masuaku", posicion: "defensa", precio: 2200000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "df_jkayembe", nombre: "Joris Kayembe", posicion: "defensa", precio: 2000000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "df_gkalulu", nombre: "Gédéon Kalulu", posicion: "defensa", precio: 1800000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "df_dbatubinsika", nombre: "Dylan Batubinsika", posicion: "defensa", precio: 1500000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "df_skapuadi", nombre: "Steve Kapuadi", posicion: "defensa", precio: 1200000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "df_atshibola", nombre: "Aaron Tshibola", posicion: "defensa", precio: 1600000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "mf_nsadiki", nombre: "Noah Sadiki", posicion: "mediocampista", precio: 1800000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "mf_ekayembe", nombre: "Edo Kayembe", posicion: "mediocampista", precio: 2400000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "mf_cpickel", nombre: "Charles Pickel", posicion: "mediocampista", precio: 2000000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "mf_nmukau", nombre: "Ngal'ayel Mukau", posicion: "mediocampista", precio: 2200000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "mf_smoutoussamy", nombre: "Samuel Moutoussamy", posicion: "mediocampista", precio: 1800000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "mf_gkakuta", nombre: "Gaël Kakuta", posicion: "mediocampista", precio: 1500000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "mf_melia", nombre: "Meschack Elia", posicion: "mediocampista", precio: 2500000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "mf_nmbuku", nombre: "Nathanaël Mbuku", posicion: "mediocampista", precio: 2000000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "mf_tbongonda", nombre: "Théo Bongonda", posicion: "mediocampista", precio: 2800000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "mf_bcipenga", nombre: "Brian Cipenga", posicion: "mediocampista", precio: 1400000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "fw_ywissa", nombre: "Yoane Wissa", posicion: "delantero", precio: 4000000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "fw_cbakambu", nombre: "Cédric Bakambu", posicion: "delantero", precio: 2500000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "fw_fmayele", nombre: "Fiston Mayele", posicion: "delantero", precio: 1800000, pais: "R.D. del Congo", flag: "🇨🇩" },
  { id: "fw_sbanza", nombre: "Simon Banza", posicion: "delantero", precio: 3200000, pais: "R.D. del Congo", flag: "🇨🇩" },

  // --- JAPÓN ---
  { id: "gk_zsuzuki", nombre: "Zion Suzuki", posicion: "portero", precio: 2500000, pais: "Japón", flag: "🇯🇵" },
  { id: "gk_kosako", nombre: "Keisuke Osako", posicion: "portero", precio: 1500000, pais: "Japón", flag: "🇯🇵" },
  { id: "gk_thayakawa", nombre: "Tomoki Hayakawa", posicion: "portero", precio: 1200000, pais: "Japón", flag: "🇯🇵" },
  { id: "df_ynagatomo", nombre: "Yuto Nagatomo", posicion: "defensa", precio: 1200000, pais: "Japón", flag: "🇯🇵" },
  { id: "df_staniguchi", nombre: "Shogo Taniguchi", posicion: "defensa", precio: 1600000, pais: "Japón", flag: "🇯🇵" },
  { id: "df_kitakura", nombre: "Ko Itakura", posicion: "defensa", precio: 3000000, pais: "Japón", flag: "🇯🇵" },
  { id: "df_twatanabe", nombre: "Tsuyoshi Watanabe", posicion: "defensa", precio: 2200000, pais: "Japón", flag: "🇯🇵" },
  { id: "df_ttomiyasu", nombre: "Takehiro Tomiyasu", posicion: "defensa", precio: 3800000, pais: "Japón", flag: "🇯🇵" },
  { id: "df_hito", nombre: "Hiroki Ito", posicion: "defensa", precio: 3500000, pais: "Japón", flag: "🇯🇵" },
  { id: "df_aseko", nombre: "Ayumu Seko", posicion: "defensa", precio: 1800000, pais: "Japón", flag: "🇯🇵" },
  { id: "df_ysugawara", nombre: "Yukinari Sugawara", posicion: "defensa", precio: 2800000, pais: "Japón", flag: "🇯🇵" },
  { id: "mf_jsuzuki", nombre: "Junnosuke Suzuki", posicion: "mediocampista", precio: 1600000, pais: "Japón", flag: "🇯🇵" },
  { id: "mf_wendo", nombre: "Wataru Endo", posicion: "mediocampista", precio: 3800000, pais: "Japón", flag: "🇯🇵" },
  { id: "mf_jito", nombre: "Junya Ito", posicion: "mediocampista", precio: 3000000, pais: "Japón", flag: "🇯🇵" },
  { id: "mf_dkamada", nombre: "Daichi Kamada", posicion: "mediocampista", precio: 3200000, pais: "Japón", flag: "🇯🇵" },
  { id: "mf_rdoan", nombre: "Ritsu Doan", posicion: "mediocampista", precio: 3500000, pais: "Japón", flag: "🇯🇵" },
  { id: "mf_atanaka", nombre: "Ao Tanaka", posicion: "mediocampista", precio: 2400000, pais: "Japón", flag: "🇯🇵" },
  { id: "mf_knakamura", nombre: "Keito Nakamura", posicion: "mediocampista", precio: 2600000, pais: "Japón", flag: "🇯🇵" },
  { id: "mf_ksano", nombre: "Kaishu Sano", posicion: "mediocampista", precio: 2000000, pais: "Japón", flag: "🇯🇵" },
  { id: "mf_tkubo", nombre: "Takefusa Kubo", posicion: "mediocampista", precio: 6000000, pais: "Japón", flag: "🇯🇵" },
  { id: "mf_ysuzuki", nombre: "Yuito Suzuki", posicion: "mediocampista", precio: 2800000, pais: "Japón", flag: "🇯🇵" },
  { id: "fw_kogawa", nombre: "Koki Ogawa", posicion: "delantero", precio: 2200000, pais: "Japón", flag: "🇯🇵" },
  { id: "fw_dmaeda", nombre: "Daizen Maeda", posicion: "delantero", precio: 2800000, pais: "Japón", flag: "🇯🇵" },
  { id: "fw_aueda", nombre: "Ayase Ueda", posicion: "delantero", precio: 3200000, pais: "Japón", flag: "🇯🇵" },
  { id: "fw_kshiogai", nombre: "Kento Shiogai", posicion: "delantero", precio: 1400000, pais: "Japón", flag: "🇯🇵" },
  { id: "fw_kgoto", nombre: "Keisuke Goto", posicion: "delantero", precio: 1600000, pais: "Japón", flag: "🇯🇵" },

  // --- COSTA DE MARFIL ---
  { id: "gk_yfofana", nombre: "Yahia Fofana", posicion: "portero", precio: 2400000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "gk_mkone", nombre: "Mohamed Koné", posicion: "portero", precio: 1500000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "gk_alafont", nombre: "Alban Lafont", posicion: "portero", precio: 2800000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "df_eagbadou", nombre: "Emmanuel Agbadou", posicion: "defensa", precio: 2200000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "df_cakpa", nombre: "Clément Akpa", posicion: "defensa", precio: 1800000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "df_odiomande", nombre: "Ousmane Diomande", posicion: "defensa", precio: 3800000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "df_gdoue", nombre: "Guela Doué", posicion: "defensa", precio: 2400000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "df_gkonan", nombre: "Ghislain Konan", posicion: "defensa", precio: 1800000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "df_okossounou", nombre: "Odilon Kossounou", posicion: "defensa", precio: 3500000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "df_endicka", nombre: "Evan Ndicka", posicion: "defensa", precio: 3800000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "df_wsingo", nombre: "Wilfried Singo", posicion: "defensa", precio: 3000000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "mf_sfofana", nombre: "Seko Fofana", posicion: "mediocampista", precio: 3500000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "mf_pguiagon", nombre: "Parfait Guiagon", posicion: "mediocampista", precio: 2000000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "mf_coulai", nombre: "Christ Inao Oulaï", posicion: "mediocampista", precio: 1500000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "mf_fkessie", nombre: "Franck Kessié", posicion: "mediocampista", precio: 4000000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "mf_isangare", nombre: "Ibrahim Sangaré", posicion: "mediocampista", precio: 3200000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "mf_jmseri", nombre: "Jean-Michaël Seri", posicion: "mediocampista", precio: 1800000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "fw_sadingra", nombre: "Simon Adingra", posicion: "delantero", precio: 4200000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "fw_aybonny", nombre: "Ange-Yoan Bonny", posicion: "delantero", precio: 3800000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "fw_adiallo", nombre: "Amad Diallo", posicion: "delantero", precio: 4500000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "fw_odiakite", nombre: "Oumar Diakité", posicion: "delantero", precio: 2600000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "fw_ydiomande", nombre: "Yan Diomande", posicion: "delantero", precio: 2000000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "fw_eguessand", nombre: "Evann Guessand", posicion: "delantero", precio: 3000000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "fw_npepe", nombre: "Nicolas Pépé", posicion: "delantero", precio: 2800000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "fw_btoure", nombre: "Bazoumana Touré", posicion: "delantero", precio: 2200000, pais: "Costa de Marfil", flag: "🇨🇮" },
  { id: "fw_ewahi", nombre: "Elye Wahi", posicion: "delantero", precio: 3500000, pais: "Costa de Marfil", flag: "🇨🇮" },

  // --- TÚNEZ ---
  { id: "gk_adahmen", nombre: "Aymen Dahmen", posicion: "portero", precio: 1200000, pais: "Túnez", flag: "🇹🇳" },
  { id: "gk_benhessen", nombre: "Sabri Ben Hessen", posicion: "portero", precio: 1000000, pais: "Túnez", flag: "🇹🇳" },
  { id: "gk_achamakh", nombre: "Abdelmouhib Chamakh", posicion: "portero", precio: 800000, pais: "Túnez", flag: "🇹🇳" },
  { id: "df_mtalbi", nombre: "Montassar Talbi", posicion: "defensa", precio: 2000000, pais: "Túnez", flag: "🇹🇳" },
  { id: "df_dbronn", nombre: "Dylan Bronn", posicion: "defensa", precio: 1800000, pais: "Túnez", flag: "🇹🇳" },
  { id: "df_orekik", nombre: "Omar Rekik", posicion: "defensa", precio: 1500000, pais: "Túnez", flag: "🇹🇳" },
  { id: "df_yvalery", nombre: "Yan Valery", posicion: "defensa", precio: 1800000, pais: "Túnez", flag: "🇹🇳" },
  { id: "df_aabdi", nombre: "Ali Abdi", posicion: "defensa", precio: 2200000, pais: "Túnez", flag: "🇹🇳" },
  { id: "df_mneffati", nombre: "Moutaz Neffati", posicion: "defensa", precio: 1200000, pais: "Túnez", flag: "🇹🇳" },
  { id: "df_rchikhaoui", nombre: "Raed Chikhaoui", posicion: "defensa", precio: 1000000, pais: "Túnez", flag: "🇹🇳" },
  { id: "df_aarous", nombre: "Adam Arous", posicion: "defensa", precio: 1200000, pais: "Túnez", flag: "🇹🇳" },
  { id: "df_benhamida", nombre: "Mohamed Amine Ben Hamida", posicion: "defensa", precio: 1400000, pais: "Túnez", flag: "🇹🇳" },
  { id: "mf_eskhiri", nombre: "Ellyes Skhiri", posicion: "mediocampista", precio: 3500000, pais: "Túnez", flag: "🇹🇳" },
  { id: "mf_hmejbri", nombre: "Hannibal Mejbri", posicion: "mediocampista", precio: 2600000, pais: "Túnez", flag: "🇹🇳" },
  { id: "mf_abenslimane", nombre: "Anis Ben Slimane", posicion: "mediocampista", precio: 2000000, pais: "Túnez", flag: "🇹🇳" },
  { id: "mf_hmahmoud", nombre: "Hadj Mahmoud", posicion: "mediocampista", precio: 1600000, pais: "Túnez", flag: "🇹🇳" },
  { id: "mf_rkhedira", nombre: "Rani Khedira", posicion: "mediocampista", precio: 2500000, pais: "Túnez", flag: "🇹🇳" },
  { id: "mf_benouanes", nombre: "Mortadha Ben Ouanes", posicion: "mediocampista", precio: 1800000, pais: "Túnez", flag: "🇹🇳" },
  { id: "fw_eachouri", nombre: "Elias Achouri", posicion: "delantero", precio: 2400000, pais: "Túnez", flag: "🇹🇳" },
  { id: "fw_igharbi", nombre: "Ismaël Gharbi", posicion: "delantero", precio: 2200000, pais: "Túnez", flag: "🇹🇳" },
  { id: "fw_esaad", nombre: "Elias Saad", posicion: "delantero", precio: 2000000, pais: "Túnez", flag: "🇹🇳" },
  { id: "fw_stounekti", nombre: "Sebastian Tounekti", posicion: "delantero", precio: 1500000, pais: "Túnez", flag: "🇹🇳" },
  { id: "fw_fchaouat", nombre: "Firas Chaouat", posicion: "delantero", precio: 1600000, pais: "Túnez", flag: "🇹🇳" },
  { id: "fw_kayari", nombre: "Khalil Ayari", posicion: "delantero", precio: 1800000, pais: "Túnez", flag: "🇹🇳" },
  { id: "fw_hmastouri", nombre: "Hazem Mastouri", posicion: "delantero", precio: 1400000, pais: "Túnez", flag: "🇹🇳" },
  { id: "fw_relloumi", nombre: "Rayan Elloumi", posicion: "delantero", precio: 1200000, pais: "Túnez", flag: "🇹🇳" },

  // --- HAITÍ ---
  { id: "gk_jplacide", nombre: "Johny Placide", posicion: "portero", precio: 1200000, pais: "Haití", flag: "🇭🇹" },
  { id: "gk_apierre", nombre: "Alexandre Pierre", posicion: "portero", precio: 1000000, pais: "Haití", flag: "🇭🇹" },
  { id: "gk_jduverger", nombre: "Josue Duverger", posicion: "portero", precio: 800000, pais: "Haití", flag: "🇭🇹" },
  { id: "df_carcus", nombre: "Carlens Arcus", posicion: "defensa", precio: 1600000, pais: "Haití", flag: "🇭🇹" },
  { id: "df_jkduverne", nombre: "Jean-Kevin Duverne", posicion: "defensa", precio: 2000000, pais: "Haití", flag: "🇭🇹" },
  { id: "df_hdelcroix", nombre: "Hannes Delcroix", posicion: "defensa", precio: 2200000, pais: "Haití", flag: "🇭🇹" },
  { id: "df_dlacroix", nombre: "Duke Lacroix", posicion: "defensa", precio: 1000000, pais: "Haití", flag: "🇭🇹" },
  { id: "df_mexperience", nombre: "Martin Experience", posicion: "defensa", precio: 1200000, pais: "Haití", flag: "🇭🇹" },
  { id: "df_wpaugain", nombre: "Wilguens Paugain", posicion: "defensa", precio: 1200000, pais: "Haití", flag: "🇭🇹" },
  { id: "df_rade", nombre: "Ricardo Ade", posicion: "defensa", precio: 1400000, pais: "Haití", flag: "🇭🇹" },
  { id: "df_kthermoncy", nombre: "Keeto Thermoncy", posicion: "defensa", precio: 1000000, pais: "Haití", flag: "🇭🇹" },
  { id: "mf_jrbellegarde", nombre: "Jean-Ricner Bellegarde", posicion: "mediocampista", precio: 2800000, pais: "Haití", flag: "🇭🇹" },
  { id: "mf_jcasimir", nombre: "Josue Casimir", posicion: "mediocampista", precio: 2000000, pais: "Haití", flag: "🇭🇹" },
  { id: "mf_djeanjacques", nombre: "Danley Jean-Jacques", posicion: "mediocampista", precio: 1800000, pais: "Haití", flag: "🇭🇹" },
  { id: "mf_lpierre", nombre: "Leverton Pierre", posicion: "mediocampista", precio: 1500000, pais: "Haití", flag: "🇭🇹" },
  { id: "mf_dsimon", nombre: "Dominique Simon", posicion: "mediocampista", precio: 1000000, pais: "Haití", flag: "🇭🇹" },
  { id: "mf_csainte", nombre: "Carl Fred Sainte", posicion: "mediocampista", precio: 1200000, pais: "Haití", flag: "🇭🇹" },
  { id: "mf_wpierre", nombre: "Woodensky Pierre", posicion: "mediocampista", precio: 800000, pais: "Haití", flag: "🇭🇹" },
  { id: "fw_detienne", nombre: "Derrick Etienne Jr.", posicion: "delantero", precio: 1600000, pais: "Haití", flag: "🇭🇹" },
  { id: "fw_wisidor", nombre: "Wilson Isidor", posicion: "delantero", precio: 2500000, pais: "Haití", flag: "🇭🇹" },
  { id: "fw_ljoseph", nombre: "Lenny Joseph", posicion: "delantero", precio: 2000000, pais: "Haití", flag: "🇭🇹" },
  { id: "fw_ddeedson", nombre: "Don Deedson Louicius", posicion: "delantero", precio: 1800000, pais: "Haití", flag: "🇭🇹" },
  { id: "fw_dnazon", nombre: "Duckens Nazon", posicion: "delantero", precio: 2000000, pais: "Haití", flag: "🇭🇹" },
  { id: "fw_fpierrot", nombre: "Frantzdy Pierrot", posicion: "delantero", precio: 2400000, pais: "Haití", flag: "🇭🇹" },
  { id: "fw_rprovidence", nombre: "Ruben Providence", posicion: "delantero", precio: 1800000, pais: "Haití", flag: "🇭🇹" },
  { id: "fw_yfortune", nombre: "Yassin Fortune", posicion: "delantero", precio: 1500000, pais: "Haití", flag: "🇭🇹" },

  // --- NUEVA ZELANDA ---
  { id: "gk_mcrocombe", nombre: "Max Crocombe", posicion: "portero", precio: 1400000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "gk_apaulsen", nombre: "Alex Paulsen", posicion: "portero", precio: 1600000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "gk_mwoud", nombre: "Michael Woud", posicion: "portero", precio: 1000000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "df_tpayne", nombre: "Tim Payne", posicion: "defensa", precio: 1200000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "df_fdevries", nombre: "Francis De Vries", posicion: "defensa", precio: 1200000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "df_tbindon", nombre: "Tyler Bindon", posicion: "defensa", precio: 2200000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "df_mboxall", nombre: "Michael Boxall", posicion: "defensa", precio: 1400000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "df_lcacace", nombre: "Liberato Cacace", posicion: "defensa", precio: 2000000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "df_npijnaker", nombre: "Nando Pijnaker", posicion: "defensa", precio: 1200000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "df_fsurman", nombre: "Finn Surman", posicion: "defensa", precio: 1500000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "df_celliot", nombre: "Callan Elliot", posicion: "defensa", precio: 1000000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "df_tsmith", nombre: "Tommy Smith", posicion: "defensa", precio: 800000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "mf_jbell", nombre: "Joe Bell", posicion: "mediocampista", precio: 1800000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "mf_mgarbett", nombre: "Matt Garbett", posicion: "mediocampista", precio: 1600000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "mf_mstamenic", nombre: "Marko Stamenic", posicion: "mediocampista", precio: 2200000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "mf_ssingh", nombre: "Sarpreet Singh", posicion: "mediocampista", precio: 1800000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "mf_arufer", nombre: "Alex Rufer", posicion: "mediocampista", precio: 1200000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "mf_rthomas", nombre: "Ryan Thomas", posicion: "mediocampista", precio: 1500000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "fw_cwood", nombre: "Chris Wood", posicion: "delantero", precio: 4000000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "fw_ejust", nombre: "Eli Just", posicion: "delantero", precio: 1500000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "fw_kbarbarouses", nombre: "Kosta Barbarouses", posicion: "delantero", precio: 1200000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "fw_bwaine", nombre: "Ben Waine", posicion: "delantero", precio: 1400000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "fw_bold", nombre: "Ben Old", posicion: "delantero", precio: 2000000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "fw_cmccowatt", nombre: "Callum McCowatt", posicion: "delantero", precio: 1400000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "fw_jrandall", nombre: "Jesse Randall", posicion: "delantero", precio: 1000000, pais: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "fw_lbayliss", nombre: "Lachlan Bayliss", posicion: "delantero", precio: 1000000, pais: "Nueva Zelanda", flag: "🇳🇿" },

  // --- SUECIA ---
  { id: "gk_knordfeldt", nombre: "Kristoffer Nordfeldt", posicion: "portero", precio: 1400000, pais: "Suecia", flag: "🇸🇪" },
  { id: "gk_vjohansson", nombre: "Viktor Johansson", posicion: "portero", precio: 2500000, pais: "Suecia", flag: "🇸🇪" },
  { id: "gk_jzetterstrom", nombre: "Jacob Widell Zetterström", posicion: "portero", precio: 1800000, pais: "Suecia", flag: "🇸🇪" },
  { id: "df_lindelof", nombre: "Victor Lindelöf", posicion: "defensa", precio: 3500000, pais: "Suecia", flag: "🇸🇪" },
  { id: "df_ihien", nombre: "Isak Hien", posicion: "defensa", precio: 3200000, pais: "Suecia", flag: "🇸🇪" },
  { id: "df_gudmundsson", nombre: "Gabriel Gudmundsson", posicion: "defensa", precio: 2400000, pais: "Suecia", flag: "🇸🇪" },
  { id: "df_cstarfelt", nombre: "Carl Starfelt", posicion: "defensa", precio: 2200000, pais: "Suecia", flag: "🇸🇪" },
  { id: "df_eholm", nombre: "Emil Holm", posicion: "defensa", precio: 2800000, pais: "Suecia", flag: "🇸🇪" },
  { id: "df_hekdal", nombre: "Hjalmar Ekdal", posicion: "defensa", precio: 2000000, pais: "Suecia", flag: "🇸🇪" },
  { id: "df_dsvensson", nombre: "Daniel Svensson", posicion: "defensa", precio: 2600000, pais: "Suecia", flag: "🇸🇪" },
  { id: "df_glagerbielke", nombre: "Gustaf Lagerbielke", posicion: "defensa", precio: 1800000, pais: "Suecia", flag: "🇸🇪" },
  { id: "df_esmith", nombre: "Eric Smith", posicion: "defensa", precio: 1600000, pais: "Suecia", flag: "🇸🇪" },
  { id: "df_estroud", nombre: "Elliot Stroud", posicion: "defensa", precio: 1200000, pais: "Suecia", flag: "🇸🇪" },
  { id: "mf_msvanberg", nombre: "Mattias Svanberg", posicion: "mediocampista", precio: 3000000, pais: "Suecia", flag: "🇸🇪" },
  { id: "mf_jkarlstrom", nombre: "Jesper Karlström", posicion: "mediocampista", precio: 2400000, pais: "Suecia", flag: "🇸🇪" },
  { id: "mf_yayari", nombre: "Yasin Ayari", posicion: "mediocampista", precio: 2500000, pais: "Suecia", flag: "🇸🇪" },
  { id: "mf_lbergvall", nombre: "Lucas Bergvall", posicion: "mediocampista", precio: 3200000, pais: "Suecia", flag: "🇸🇪" },
  { id: "mf_bzeneli", nombre: "Besfort Zeneli", posicion: "mediocampista", precio: 1800000, pais: "Suecia", flag: "🇸🇪" },
  { id: "fw_aisak", nombre: "Alexander Isak", posicion: "delantero", precio: 8500000, pais: "Suecia", flag: "🇸🇪" },
  { id: "fw_vgyokeres", nombre: "Viktor Gyökeres", posicion: "delantero", precio: 9000000, pais: "Suecia", flag: "🇸🇪" },
  { id: "fw_ksema", nombre: "Ken Sema", posicion: "delantero", precio: 1800000, pais: "Suecia", flag: "🇸🇪" },
  { id: "fw_aelanga", nombre: "Anthony Elanga", posicion: "delantero", precio: 4000000, pais: "Suecia", flag: "🇸🇪" },
  { id: "fw_bnygren", nombre: "Benjamin Nygren", posicion: "delantero", precio: 2200000, pais: "Suecia", flag: "🇸🇪" },
  { id: "fw_abernhardsson", nombre: "Alexander Bernhardsson", posicion: "delantero", precio: 1800000, pais: "Suecia", flag: "🇸🇪" },
  { id: "fw_gnilsson", nombre: "Gustaf Nilsson", posicion: "delantero", precio: 2400000, pais: "Suecia", flag: "🇸🇪" },
  { id: "fw_tali", nombre: "Taha Ali", posicion: "delantero", precio: 1600000, pais: "Suecia", flag: "🇸🇪" },

  // --- BOSNIA Y HERZEGOVINA ---
  { id: "gk_nvasilj", nombre: "Nikola Vasilj", posicion: "portero", precio: 1800000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "gk_mzlomislic", nombre: "Martin Zlomislić", posicion: "portero", precio: 1400000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "gk_ohadzikic", nombre: "Osman Hadžikić", posicion: "portero", precio: 1200000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "df_skolasinac", nombre: "Sead Kolašinac", posicion: "defensa", precio: 2500000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "df_dhadzikadunic", nombre: "Dennis Hadžikadunić", posicion: "defensa", precio: 2000000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "df_adedic", nombre: "Amar Dedić", posicion: "defensa", precio: 3000000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "df_nkatic", nombre: "Nikola Katić", posicion: "defensa", precio: 1800000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "df_tmuharemovic", nombre: "Tarik Muharemović", posicion: "defensa", precio: 1600000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "df_nmujakic", nombre: "Nihad Mujakić", posicion: "defensa", precio: 1400000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "df_sradeljic", nombre: "Stjepan Radeljić", posicion: "defensa", precio: 1500000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "df_ncelik", nombre: "Nidal Čelik", posicion: "defensa", precio: 1200000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "mf_ahadziahmetovic", nombre: "Amir Hadžiahmetović", posicion: "mediocampista", precio: 2200000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "mf_btahirovic", nombre: "Benjamin Tahirović", posicion: "mediocampista", precio: 2000000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "mf_agigovic", nombre: "Armin Gigović", posicion: "mediocampista", precio: 1800000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "mf_dburnic", nombre: "Dženis Burnić", posicion: "mediocampista", precio: 1500000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "mf_ibasic", nombre: "Ivan Bašić", posicion: "mediocampista", precio: 1600000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "mf_ebajraktarevic", nombre: "Esmir Bajraktarević", posicion: "mediocampista", precio: 2200000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "mf_amemic", nombre: "Amar Memić", posicion: "mediocampista", precio: 1400000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "mf_isunjic", nombre: "Ivan Šunjić", posicion: "mediocampista", precio: 1800000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "mf_kalajbegovic", nombre: "Kerim Alajbegović", posicion: "mediocampista", precio: 2000000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "mf_emahmic", nombre: "Ermin Mahmić", posicion: "mediocampista", precio: 1200000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "fw_edzeko", nombre: "Edin Džeko", posicion: "delantero", precio: 3000000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "fw_edemirovic", nombre: "Ermedin Demirović", posicion: "delantero", precio: 3500000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "fw_sbazdar", nombre: "Samed Baždar", posicion: "delantero", precio: 2000000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "fw_htabakovic", nombre: "Haris Tabaković", posicion: "delantero", precio: 2200000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { id: "fw_jlukic", nombre: "Jovo Lukić", posicion: "delantero", precio: 1500000, pais: "Bosnia y Herzegovina", flag: "🇧🇦" }
];
